/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopatito;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GUILINTON323
 */

public class MenuSupervisor extends javax.swing.JFrame {

    /**
     * Creates new form MenuSupervisor
     */
        DefaultTableModel modeloPatito;      
    public MenuSupervisor() {
        initComponents();
        setLocationRelativeTo(null);
        coincidencia("");         
    }

        public void coincidencia(String texto){
        
        try{
            String [] titulos = {"ID", "USUARIO", "PASSWORD", "NIVEL"};
            String [] registros = new String [4];

            modeloPatito = new DefaultTableModel(null, titulos);
            
            Conectar conectar = new Conectar();
            Connection conexionPatito = conectar.conexion();

            String sql = "";
            sql = "SELECT * FROM usuarios";
            
            PreparedStatement statementPatito = conexionPatito.prepareStatement(sql);
            ResultSet resultsetPatito = statementPatito.executeQuery(sql);
            
             while (resultsetPatito.next()){
                registros [0] = resultsetPatito.getString("id");
                registros [1] = resultsetPatito.getString("usuario");
                registros [2] = resultsetPatito.getString("password");
                registros [3] = resultsetPatito.getString("nivel");
                            
                 modeloPatito.addRow(registros);    
            }
            TablaPatito.setModel(modeloPatito);
        }catch (SQLException e){
     System.out.println(e.getMessage());
    }

    }     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NIVELES = new javax.swing.ButtonGroup();
        NIVELES2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        etiFiltro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPatito = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPas = new javax.swing.JTextField();
        opcUno = new javax.swing.JRadioButton();
        opcDos = new javax.swing.JRadioButton();
        opcTres = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtUsu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        opc1 = new javax.swing.JRadioButton();
        opc2 = new javax.swing.JRadioButton();
        opc3 = new javax.swing.JRadioButton();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnRefrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU DEL SUPERVISOR PATITO");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiFiltro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(etiFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 40, -1, -1));

        jLabel3.setText("EN EL CUADRO DE ABAJO SE MUESTRAN LOS USUARIOS AUTORIZADOS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, -1, -1));

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setText("CERRAR SESIÓN");
        btnSalir.setToolTipText("Cerrar la sesión del Supervisor Patito");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 11, -1, -1));

        TablaPatito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaPatito.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaPatito);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 506, 75));

        jLabel1.setText("AGREGAR NUEVO USUARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, -1, -1));

        jLabel4.setText("NOMBRE DE USUSARIO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 184, -1, -1));

        jLabel5.setText("PASSWORD");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 233, -1, -1));

        jLabel6.setText("NIVEL");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 282, -1, -1));
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 204, 158, -1));

        txtPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasActionPerformed(evt);
            }
        });
        jPanel1.add(txtPas, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 282, 158, -1));

        NIVELES.add(opcUno);
        opcUno.setText("(1) SUPERVISOR");
        jPanel1.add(opcUno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 298, -1, -1));

        NIVELES.add(opcDos);
        opcDos.setText("(2) ADMINISTRADOR");
        jPanel1.add(opcDos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 321, -1, -1));

        NIVELES.add(opcTres);
        opcTres.setText("(3) ASISTENTE");
        opcTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcTresActionPerformed(evt);
            }
        });
        jPanel1.add(opcTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 344, -1, -1));

        jLabel2.setText("ACTUALIZAR O BORRAR USUARIO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 139, -1, -1));
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 176, 38, -1));

        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jPanel1.add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 175, -1, -1));

        jLabel7.setText("NOMBRE DE USUSARIO");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 207, -1, -1));
        jPanel1.add(txtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 230, 158, -1));

        jLabel8.setText("PASSWORD");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 259, -1, -1));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 256, 158, -1));

        jLabel9.setText("NIVEL ACTUAL");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 308, -1, -1));

        txtNivel.setEditable(false);
        txtNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNivelActionPerformed(evt);
            }
        });
        jPanel1.add(txtNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 328, 50, -1));

        jLabel10.setText("ACTUALIZAR NIVEL");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 359, -1, -1));

        NIVELES2.add(opc1);
        opc1.setText("(1) SUPERVISOR");
        jPanel1.add(opc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 375, -1, -1));

        NIVELES2.add(opc2);
        opc2.setText("(2) ADMINISTRADOR");
        opc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc2ActionPerformed(evt);
            }
        });
        jPanel1.add(opc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 398, -1, -1));

        NIVELES2.add(opc3);
        opc3.setText("(3) ASISTENTE");
        jPanel1.add(opc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 421, -1, -1));

        btnAgregar.setText("AGREGAR USUARIO");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 385, -1, -1));

        btnActualizar.setText("ACTUALIZAR USUARIO");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 451, -1, -1));

        btnBorrar.setText("BORRAR USUARIO");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 451, -1, -1));

        jLabel11.setText("INGRESE EL ID DE USUARIO");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 159, 158, -1));

        btnRefrescar.setText("REFRESCAR DATOS");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefrescar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        LoginSistemaPatito login = new LoginSistemaPatito();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasActionPerformed

    private void opcTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcTresActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNivelActionPerformed

    private void opc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc2ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
try{
    Conectar conectar = new Conectar();
    Connection conexionPatito = conectar.conexion();
    
    String paraUsuario;
    String paraPassword;
    int paraNivel=0;
    String sql = "";
    
    paraUsuario = txtUsuario.getText();
    paraPassword = txtPassword.getText();
    
    if (opcUno.isSelected()){
        paraNivel = 1;
    }else if(opcDos.isSelected()){
        paraNivel = 2;   
    }else if(opcTres.isSelected()){
       paraNivel = 3;
    }
    sql = "insert into usuarios (usuario, password, nivel) values (?, ?, ?)";
    
    PreparedStatement statementPatito = conexionPatito.prepareStatement(sql);
    statementPatito.setString(1, paraUsuario);
    statementPatito.setString(2, paraPassword);
    statementPatito.setInt(3, paraNivel);
       
    int p = statementPatito.executeUpdate();
    if (p > 0){
        JOptionPane.showMessageDialog(null, "El Registro de Usuario fue Guardado");
        
    conexionPatito.close();
    
    }
}catch(SQLException e){
        System.out.println(e.getMessage());
}

txtUsuario.setText("");
txtPassword.setText("");
NIVELES.clearSelection();
        
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try{
            Conectar conectar = new Conectar();
            Connection conexionPatito = conectar.conexion();
            String sql="";
            sql = "SELECT * FROM usuarios WHERE id=?";
            PreparedStatement statementPatito = conexionPatito.prepareStatement(sql);
            statementPatito.setString(1, txtId.getText());
            ResultSet resultsetPatito = statementPatito.executeQuery();
            if (resultsetPatito.next()){
                txtUsu.setText(resultsetPatito.getString("usuario"));
                txtPas.setText(resultsetPatito.getString("password"));
                txtNivel.setText(resultsetPatito.getString("nivel"));

            }else{
                JOptionPane.showMessageDialog(null,"No exite el Usuario");
txtId.setText("");                
txtUsu.setText("");
txtPas.setText("");
txtNivel.setText("");                
txtId.requestFocus();
            }
            conexionPatito.close();

        }catch (SQLException e){
            System.out.println(e.getMessage());
        }

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        
    int paraNivel=0;
        if (opc1.isSelected()){
        paraNivel = 1;
    }else if(opc2.isSelected()){
        paraNivel = 2;   
    }else if(opc3.isSelected()){
       paraNivel = 3;
    }
        try{
           Conectar conectar = new Conectar();
           Connection conexionPatito = conectar.conexion();
           String sql="";
           sql = "update usuarios SET  usuario=?, password=?, nivel=? WHERE id=?";
          
           PreparedStatement statementPatito = conexionPatito.prepareStatement(sql);
           statementPatito.setString(1, txtUsu.getText());
           statementPatito.setString(2, txtPas.getText());
           statementPatito.setInt(3, paraNivel);
           statementPatito.setString(4, txtId.getText());
                     
           int respuesta = statementPatito.executeUpdate();
           
           if (respuesta>0){
               JOptionPane.showMessageDialog(null,"Registro ACTUALIZADO");
           }else{
                JOptionPane.showMessageDialog(null,"NO se pudo actualizar el registro");
           }
         
            conexionPatito.close();
       }catch (SQLException e){
        System.out.println(e.getMessage());
        } 
        
        txtUsu.setText("");
        txtPas.setText("");
        txtNivel.setText("");
        NIVELES2.clearSelection();
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

    try{
           Conectar conectar = new Conectar();
           Connection conexionPatito = conectar.conexion();
           String sql="";
           sql = "delete from usuarios where id=?";
           
           PreparedStatement statementPatito = conexionPatito.prepareStatement(sql);        
           statementPatito.setInt(1, Integer.parseInt(txtId.getText()));
           
           int opcion = statementPatito.executeUpdate();
           if (opcion > 0){
               JOptionPane.showMessageDialog(null,"El registro del usuario SE BORRO de la Base de Datos");
           }else{
                JOptionPane.showMessageDialog(null,"Registro NO BORRADO - por favor revise");
           }       
 
           conexionPatito.close();               
           }catch (SQLException e){
        System.out.println(e.getMessage());
        }   
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed

        coincidencia("");

    }//GEN-LAST:event_btnRefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSupervisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup NIVELES;
    private javax.swing.ButtonGroup NIVELES2;
    private javax.swing.JTable TablaPatito;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel etiFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opc1;
    private javax.swing.JRadioButton opc2;
    private javax.swing.JRadioButton opc3;
    private javax.swing.JRadioButton opcDos;
    private javax.swing.JRadioButton opcTres;
    private javax.swing.JRadioButton opcUno;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtPas;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsu;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
