/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopatito;

import javax.swing.JOptionPane;

/**
 *
 * @author GUILINTON323
 */
public class MenuSecundarioPatito extends javax.swing.JFrame {

    /**
     * Creates new form MenuSecundarioPatito
     */
    public MenuSecundarioPatito() {
        initComponents();
        setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        itemConsulta = new javax.swing.JMenuItem();
        menuServicios = new javax.swing.JMenu();
        itemCable = new javax.swing.JMenuItem();
        itemInternet = new javax.swing.JMenuItem();
        itemCombo = new javax.swing.JMenuItem();
        itemImprimir = new javax.swing.JMenu();
        itemCrear = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemReporte = new javax.swing.JMenuItem();
        itemReportes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU DEL ASISTENTE / SISTEMA CABLENET PATITO");

        jPanel1.setBackground(java.awt.Color.white);

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSalir.setText("SALIR DEL SISTEMA");
        btnSalir.setToolTipText("Cerrar la sesión de usuario del SISTEMA PATITO");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/prueba.png"))); // NOI18N
        jLabel1.setAutoscrolls(true);
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap(186, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        menuClientes.setBorder(null);
        menuClientes.setText("CLIENTES");
        menuClientes.setToolTipText("Control de clientes, para agregar o eliminar clientes de la base de datos PATITO");
        menuClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuClientes.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        menuClientes.setMaximumSize(new java.awt.Dimension(150, 32767));

        itemConsulta.setText("CONSULTAS");
        itemConsulta.setToolTipText("Agregar registros de nuevos clientes a la base de datos PATITO");
        itemConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultaActionPerformed(evt);
            }
        });
        menuClientes.add(itemConsulta);

        jMenuBar1.add(menuClientes);

        menuServicios.setText("SERVICIOS");
        menuServicios.setToolTipText("Muestra los servicios que provee la empresa (no se puede editar)");
        menuServicios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuServicios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuServicios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuServicios.setMaximumSize(new java.awt.Dimension(150, 32767));

        itemCable.setText("CABLE (CÓDIGO 1)");
        itemCable.setToolTipText("Muestra las características del servicio");
        itemCable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCableActionPerformed(evt);
            }
        });
        menuServicios.add(itemCable);

        itemInternet.setText("INTERNET (CÓDIGO 2)");
        itemInternet.setToolTipText("Muestra las características del servicio");
        itemInternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInternetActionPerformed(evt);
            }
        });
        menuServicios.add(itemInternet);

        itemCombo.setText("CABLE E INTERNET (CÓDIGO 3)");
        itemCombo.setToolTipText("Muestra las características del servicio");
        itemCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComboActionPerformed(evt);
            }
        });
        menuServicios.add(itemCombo);

        jMenuBar1.add(menuServicios);

        itemImprimir.setText("FACTURACIÓN");
        itemImprimir.setToolTipText("Control de la facturación de PATITO");
        itemImprimir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        itemImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        itemImprimir.setMaximumSize(new java.awt.Dimension(150, 32767));

        itemCrear.setText("CREAR FACTURA");
        itemCrear.setToolTipText("Creación del comprobante que recibe el cliente al pagar el servicio contratado");
        itemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCrearActionPerformed(evt);
            }
        });
        itemImprimir.add(itemCrear);

        jMenuItem1.setText("IMPRIMIR FACTURA");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        itemImprimir.add(jMenuItem1);

        jMenuBar1.add(itemImprimir);

        menuReportes.setText("REPORTES");
        menuReportes.setToolTipText("Permite visualizar el record de pago de los clientes y los comprobantes de pago emitidos (facturas)");
        menuReportes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        menuReportes.setMaximumSize(new java.awt.Dimension(150, 32767));

        itemReporte.setText("VER FACTURACIÓN POR CLIENTE");
        itemReporte.setToolTipText("Visualizar record de pago de los clientes");
        itemReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReporteActionPerformed(evt);
            }
        });
        menuReportes.add(itemReporte);

        itemReportes.setText("IMPRIMIR FACTURACIÓN POR CLIENTE");
        itemReportes.setToolTipText("Obtener un reporte físico de facturación");
        itemReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReportesActionPerformed(evt);
            }
        });
        menuReportes.add(itemReportes);

        jMenuBar1.add(menuReportes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCableActionPerformed

        JOptionPane.showMessageDialog(null, "TV por cable 110 canales en HD, costo mensual del servicio Q100.00, código de servicio 1");

    }//GEN-LAST:event_itemCableActionPerformed

    private void itemInternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInternetActionPerformed

        JOptionPane.showMessageDialog(null, "Interner de alta velocidad 4G, cargas y descargas de archivos ilimitados, costo mensual del servicio Q200.00, codigo de servicio 2");
    }//GEN-LAST:event_itemInternetActionPerformed

    private void itemComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComboActionPerformed

        JOptionPane.showMessageDialog(null, "Combo TV por cable 110 canales en HD + Interner de alta velocidad 4G, cargas y descargas de archivos ilimitados, costo del servicio Q250.00");
    }//GEN-LAST:event_itemComboActionPerformed

    private void itemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCrearActionPerformed

        CrearFactura1 crear = new CrearFactura1();
        crear.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemCrearActionPerformed

    private void itemReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReporteActionPerformed

        ReportePatito1 reporteFacturacion = new ReportePatito1();
        reporteFacturacion.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemReporteActionPerformed

    private void itemReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReportesActionPerformed
        ReportesPatito reporteFacturacion = new ReportesPatito();
        reporteFacturacion.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_itemReportesActionPerformed

    private void itemConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultaActionPerformed

        ConsultaRegistros1 consulta = new ConsultaRegistros1();
        consulta.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemConsultaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        //System.exit(0);
    LoginSistemaPatito login = new LoginSistemaPatito();
    login.setVisible(true);
    this.dispose();        
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FacturaCliente1 factura = new FacturaCliente1();
        factura.setVisible(true);
        this.setVisible(false);        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSecundarioPatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSecundarioPatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSecundarioPatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSecundarioPatito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSecundarioPatito().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuItem itemCable;
    private javax.swing.JMenuItem itemCombo;
    private javax.swing.JMenuItem itemConsulta;
    private javax.swing.JMenuItem itemCrear;
    private javax.swing.JMenu itemImprimir;
    private javax.swing.JMenuItem itemInternet;
    private javax.swing.JMenuItem itemReporte;
    private javax.swing.JMenuItem itemReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JMenu menuServicios;
    // End of variables declaration//GEN-END:variables
}
