/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopatito;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author GUILINTON323
 */

public class MenuSupervisor extends javax.swing.JFrame {

    /**
     * Creates new form MenuSupervisor
     */
        DefaultTableModel modeloPatito;      
    public MenuSupervisor() {
        initComponents();
        setLocationRelativeTo(null);
        coincidencia("");         
    }

        public void coincidencia(String texto){
        
        try{
            String [] titulos = {"ID", "USUARIO", "PASSWORD", "NIVEL"};
            String [] registros = new String [4];

            modeloPatito = new DefaultTableModel(null, titulos);
            
            Conectar conectar = new Conectar();
            Connection conexionPatito = conectar.conexion();

            String sql = "";
            sql = "SELECT * FROM usuarios";
            
            PreparedStatement statementPatito = conexionPatito.prepareStatement(sql);
            ResultSet resultsetPatito = statementPatito.executeQuery(sql);
            
             while (resultsetPatito.next()){
                registros [0] = resultsetPatito.getString("id");
                registros [1] = resultsetPatito.getString("usuario");
                registros [2] = resultsetPatito.getString("password");
                registros [3] = resultsetPatito.getString("nivel");
                            
                 modeloPatito.addRow(registros);    
            }
            TablaPatito.setModel(modeloPatito);
        }catch (SQLException e){
     System.out.println(e.getMessage());
    }

    }     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NIVELES = new javax.swing.ButtonGroup();
        NIVELES2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        etiFiltro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPatito = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPas = new javax.swing.JTextField();
        opcUno = new javax.swing.JRadioButton();
        opcDos = new javax.swing.JRadioButton();
        opcTres = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        txtUsu = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtNivel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        opc1 = new javax.swing.JRadioButton();
        opc2 = new javax.swing.JRadioButton();
        opc3 = new javax.swing.JRadioButton();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnRefrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU DEL SUPERVISOR PATITO");

        etiFiltro.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("EN EL CUADRO DE ABAJO SE MUESTRAN LOS USUARIOS AUTORIZADOS");

        btnSalir.setBackground(new java.awt.Color(255, 0, 51));
        btnSalir.setText("CERRAR SESIÓN");
        btnSalir.setToolTipText("Cerrar la sesión del Supervisor Patito");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        TablaPatito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaPatito.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaPatito);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel1.setText("AGREGAR NUEVO USUARIO");

        jLabel6.setText("NIVEL");

        txtUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("USUARIO"));

        txtPas.setBorder(javax.swing.BorderFactory.createTitledBorder("CONTRASEÑA"));
        txtPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasActionPerformed(evt);
            }
        });

        NIVELES.add(opcUno);
        opcUno.setText("(1) SUPERVISOR");

        NIVELES.add(opcDos);
        opcDos.setText("(2) ADMINISTRADOR");

        NIVELES.add(opcTres);
        opcTres.setText("(3) ASISTENTE");
        opcTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcTresActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("ACTUALIZAR O BORRAR USUARIO");

        txtId.setBorder(javax.swing.BorderFactory.createTitledBorder("ID USUARIO"));

        btnConsultar.setText("CONSULTAR");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        txtUsu.setBorder(javax.swing.BorderFactory.createTitledBorder("USUARIO"));

        txtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder("CONTRASEÑA"));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });

        txtNivel.setEditable(false);
        txtNivel.setBorder(javax.swing.BorderFactory.createTitledBorder("NIVEL ACTUAL"));
        txtNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNivelActionPerformed(evt);
            }
        });

        jLabel10.setText("ACTUALIZAR NIVEL");

        NIVELES2.add(opc1);
        opc1.setText("(1) SUPERVISOR");

        NIVELES2.add(opc2);
        opc2.setText("(2) ADMINISTRADOR");
        opc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opc2ActionPerformed(evt);
            }
        });

        NIVELES2.add(opc3);
        opc3.setText("(3) ASISTENTE");

        btnAgregar.setText("AGREGAR USUARIO");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnActualizar.setText("ACTUALIZAR USUARIO");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBorrar.setText("BORRAR USUARIO");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnRefrescar.setText("REFRESCAR DATOS");
        btnRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPas, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(31, 31, 31)
                            .addComponent(opc1)
                            .addGap(18, 18, 18)
                            .addComponent(opc2)
                            .addGap(18, 18, 18)
                            .addComponent(opc3))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(163, 163, 163)
                            .addComponent(btnActualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(btnConsultar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addComponent(opcUno)
                        .addGap(18, 18, 18)
                        .addComponent(opcDos)
                        .addGap(18, 18, 18)
                        .addComponent(opcTres))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addComponent(etiFiltro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRefrescar)
                        .addGap(193, 193, 193)
                        .addComponent(btnSalir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etiFiltro)
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(opcUno)
                            .addComponent(opcDos)
                            .addComponent(opcTres))
                        .addGap(26, 26, 26)
                        .addComponent(btnAgregar)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConsultar))
                        .addGap(18, 18, 18)
                        .addComponent(txtUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(opc1)
                            .addComponent(opc2)
                            .addComponent(opc3))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualizar)
                            .addComponent(btnBorrar))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnRefrescar)
                                    .addComponent(btnSalir))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(131, 131, 131))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefrescarActionPerformed

        coincidencia("");
    }//GEN-LAST:event_btnRefrescarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed

        try{
            Conectar conectar = new Conectar();
            Connection conexionPatito = conectar.conexion();
            String sql="";
            sql = "delete from usuarios where id=?";

            PreparedStatement statementPatito = conexionPatito.prepareStatement(sql);
            statementPatito.setInt(1, Integer.parseInt(txtId.getText()));

            int opcion = statementPatito.executeUpdate();
            if (opcion > 0){
                JOptionPane.showMessageDialog(null,"El registro del usuario SE BORRO de la Base de Datos");
            }else{
                JOptionPane.showMessageDialog(null,"Registro NO BORRADO - por favor revise");
            }

            conexionPatito.close();
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        int paraNivel=0;
        if (opc1.isSelected()){
            paraNivel = 1;
        }else if(opc2.isSelected()){
            paraNivel = 2;
        }else if(opc3.isSelected()){
            paraNivel = 3;
        }
        try{
            Conectar conectar = new Conectar();
            Connection conexionPatito = conectar.conexion();
            String sql="";
            sql = "update usuarios SET  usuario=?, password=?, nivel=? WHERE id=?";

            PreparedStatement statementPatito = conexionPatito.prepareStatement(sql);
            statementPatito.setString(1, txtUsu.getText());
            statementPatito.setString(2, txtPas.getText());
            statementPatito.setInt(3, paraNivel);
            statementPatito.setString(4, txtId.getText());

            int respuesta = statementPatito.executeUpdate();

            if (respuesta>0){
                JOptionPane.showMessageDialog(null,"Registro ACTUALIZADO");
            }else{
                JOptionPane.showMessageDialog(null,"NO se pudo actualizar el registro");
            }

            conexionPatito.close();
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }

        txtUsu.setText("");
        txtPas.setText("");
        txtNivel.setText("");
        NIVELES2.clearSelection();

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try{
            Conectar conectar = new Conectar();
            Connection conexionPatito = conectar.conexion();

            String paraUsuario;
            String paraPassword;
            int paraNivel=0;
            String sql = "";

            paraUsuario = txtUsuario.getText();
            paraPassword = txtPassword.getText();

            if (opcUno.isSelected()){
                paraNivel = 1;
            }else if(opcDos.isSelected()){
                paraNivel = 2;
            }else if(opcTres.isSelected()){
                paraNivel = 3;
            }
            sql = "insert into usuarios (usuario, password, nivel) values (?, ?, ?)";

            PreparedStatement statementPatito = conexionPatito.prepareStatement(sql);
            statementPatito.setString(1, paraUsuario);
            statementPatito.setString(2, paraPassword);
            statementPatito.setInt(3, paraNivel);

            int p = statementPatito.executeUpdate();
            if (p > 0){
                JOptionPane.showMessageDialog(null, "El Registro de Usuario fue Guardado");

                conexionPatito.close();

            }
        }catch(SQLException e){
            System.out.println(e.getMessage());
        }

        txtUsuario.setText("");
        txtPassword.setText("");
        NIVELES.clearSelection();

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void opc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opc2ActionPerformed

    private void txtNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNivelActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try{
            Conectar conectar = new Conectar();
            Connection conexionPatito = conectar.conexion();
            String sql="";
            sql = "SELECT * FROM usuarios WHERE id=?";
            PreparedStatement statementPatito = conexionPatito.prepareStatement(sql);
            statementPatito.setString(1, txtId.getText());
            ResultSet resultsetPatito = statementPatito.executeQuery();
            if (resultsetPatito.next()){
                txtUsu.setText(resultsetPatito.getString("usuario"));
                txtPas.setText(resultsetPatito.getString("password"));
                txtNivel.setText(resultsetPatito.getString("nivel"));

            }else{
                JOptionPane.showMessageDialog(null,"No exite el Usuario");
                txtId.setText("");
                txtUsu.setText("");
                txtPas.setText("");
                txtNivel.setText("");
                txtId.requestFocus();
            }
            conexionPatito.close();

        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void opcTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcTresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcTresActionPerformed

    private void txtPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        LoginSistemaPatito login = new LoginSistemaPatito();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSupervisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSupervisor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup NIVELES;
    private javax.swing.ButtonGroup NIVELES2;
    private javax.swing.JTable TablaPatito;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnRefrescar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel etiFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opc1;
    private javax.swing.JRadioButton opc2;
    private javax.swing.JRadioButton opc3;
    private javax.swing.JRadioButton opcDos;
    private javax.swing.JRadioButton opcTres;
    private javax.swing.JRadioButton opcUno;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtPas;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsu;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
